kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: deployment-nginx
  namespace: nginx

spec:
  selector:
    matchLabels:
      app: dip


  template:
    metadata:
      labels:
        app: dip

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

