kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app-deployment
  namespace: nginx
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app

  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: rushikesh31/notes-app-k8s
          ports:
            - containerPort: 8000
          livenessProbe:  #use for the check the pod are running or not
            httpGet:
              path: /
              port: 8000
          readinessProbe: #use for the pod are creating or not
            httpGet:
              path: /
              port: 8000


