kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-nginx
  namespace: nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app: dip


  template:
    metadata:
      labels:
        app: dip

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: local-pvc

